config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :morties, only: [:new,:create,:show,:update,:index] do
    resources :reservations, only: :create
     resources :reviews, only: [:new, :create]
  end

  resources :reservations, only: [:show, :destroy, :update]
  namespace :my do
    resources :morties, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/morty.rb
class Morty < ApplicationRecord

   RARITY = ["common", "rare", "epic"]
   STATE = ["hurt","relaxed","depressed","angry"]
   PRICE = ["0-50","50-100", "100-200","200-1000"]

  has_one_attached :photo
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :price, presence: true
  validates :photo, presence: true
  validates :description, presence: true

  validates :state, inclusion: { in: STATE,
      message: "%{value} is not a valid state type" }, presence: true

  validates :rarity, inclusion: { in: RARITY,
      message: "%{value} is not a valid rarity type" }, presence: true


end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :morty
  enum progress: { pending: 0, confirmation: 1, abordation: 2 }
end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :user, inverse_of: :reviews
 belongs_to :morty
 validates :description, presence: true
 validates :rating, inclusion: { in: 0..5 }
 validates :morty_id, uniqueness: { scope: :user_id, message: "You've reviewed this morty!" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :reservations
  has_many :morties
  has_many :reviews, inverse_of: :user
  validates :first_name, :last_name,  presence: true
  has_one_attached :photo

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
  
  def confirmations
    self.reservations.where(progress: :confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/morties_controller.rb
class MortiesController < ApplicationController

  def new
    @morty = Morty.new
  end

  def create
    @morty = Morty.new(morty_params)
    @morty.user = current_user
    if @morty.save
      redirect_to morty_path(@morty)
    else
      render :new
    end
  end

  def show
    @morty = Morty.find(params[:id])
    @reservation = Reservation.find_or_initialize_by(morty: @morty)
  end

  def update
    @morty = Morty.find(params[:id])
    @reservation = @morty.reservations.last
    @reservation.confirmation!
    @reservation.save!
    redirect_to morty_path(@morty)
  end

  def index
    @morties = Morty.all
    if !(params[:request][:name].blank?)
      sql_query = "morties.name @@ :name"
      @morties = @morties.where(sql_query, name: "%#{params[:request][:name]}%")
    end
    if !(params[:request][:price].blank?)
      min = params[:request][:price].split("-").first
      max = params[:request][:price].split("-").last
      sql_query = "morties.price >= :min AND morties.price < :max"
      @morties = @morties.where(sql_query, min: min, max: max)
    end
    if !(params[:request][:state].blank?)
      sql_query = "morties.state @@ :state"
      @morties = @morties.where(sql_query, state: "%#{params[:request][:state]}%")
    end
    if !(params[:request][:rarity].blank?)
      sql_query = "morties.rarity @@ :rarity"
      @morties = @morties.where(sql_query, rarity: "%#{params[:request][:rarity]}%")
    end
  end



  private

  def morty_params
    params.require(:morty).permit(:name,:price,:description,:state,:rarity,:photo)
  end
end

app/controllers/my/morties_controller.rb
class My::MortiesController < ApplicationController 
    def index 
        @morties = current_user.morties
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @morties = Morty.all
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @morty = Morty.find(params[:morty_id])
    @reservation = Reservation.new
    @reservation.user = current_user
    @reservation.morty = @morty
    if @reservation.save
      @reservation.pending!
      redirect_to reservation_path(@reservation)
    else
      redirect_to morty_path(@morty)
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @morty = @reservation.morty
    @reservation.destroy
    redirect_to morty_path(@morty)
  end

  def update
    morty_id = Reservation.find(params[:id]).morty_id
    @morty = Morty.find(morty_id)
    @reservation = Reservation.find(params[:id])
    @reservation.favori = true
    @reservation.save
    redirect_to morty_path(@morty)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_morty, only: [:index, :new]
before_action :set_review, only: [ :edit, :update ]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.morty = Morty.find(params[:morty_id])
    @morty = @review.morty
    if @review.save
        redirect_to morty_path(@morty)
      else
        render 'morties/show'
    end
  end


  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end

  def set_morty
    @morty = Morty.find(params[:morty_id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_review
     @review = Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_navbar(element)
   if element.photo.attached?
    cl_image_tag(element.photo.key, crop: :fill, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)
   else
     image_tag("RickAvatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)
   end
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAMorty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body style="background-image:url(<%=image_path('BackgroundUniverse.png')%>)">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/morties/index.html.erb
<div class="container">
  <div class="cards-all">
          <% @morties.each do |morty| %>
            <% last_reservation = morty.reservations.last %>
            <% morty_display_image_condition = last_reservation.present? && last_reservation.confirmation? %>
            <%= render 'shared/cards-small', morty: morty, morty_display_image_condition: morty_display_image_condition %>
          <% end %>
        </div>
</div>

app/views/morties/new.html.erb
<div class="container">
  <div class="row card-large bg-light shadow p-5 mb-5 margin-top-80px bg-white d-flex justify-content-center ">
    <h1 class="header-shadow">Add my Morty</h1>
    <div class="mx-auto">
      <br>
      <%= simple_form_for @morty do |f| %>
        <%= f.input :name, placeholder: "Robot Morty" %>
        <%= f.input :price, label: "My lovely Morty is this much", placeholder: "36 Dollars" %>
        <%= f.input :description, placeholder: "Well designed Morty" %>
        <%= f.input :state, label: "Choose between hurt relaxed depressed and angry", placeholder: "Angry" , collection: Morty::STATE  %>
        <%= f.input :rarity, label: "Choose between commun rare and epic", placeholder: "Epic" , collection: Morty::RARITY %>
        <br>
        <%= f.input :photo, as: :file, label: "Choose a nice picture for your Morty" %>
        <br>
        <hr>
        <%= f.button :submit, "Share my Morty", class: "btn-black"%>
      <% end %>
    </div>
  </div>
</div>

app/views/morties/show.html.erb
<div class="container">
  <div class="row card-large bg-light shadow p-5 mb-5 margin-top-80px bg-white d-flex justify-content-center ">
    <div class="header-shadow"><%= @morty.name %> </div>
    <div class="col-sm-offset-2 col-sm-8 d-flex justify-content-between">
      <% if @reservation.confirmation? %>
      <%= image_tag "booked.png", alt: "booked", id: "booked-img" %>
      <% end %>
      <div>
        <font size="+1">
          <span class="highlight"><i>Description :</i></span>
          <p><i><%= @morty.description.capitalize %></i></p>
          <span class="highlight"><i>State :</i></span>
          <p><i><%= @morty.state.capitalize %></i></p>
          <span class="highlight"><i>Rarity :</i></span>
          <p><i><%= @morty.rarity.capitalize %></i></p>
          <span class="highlight"><i>Owner :</i></span>
          <p> <i><%= @morty.user.full_name %></i></p>
          <span class="highlight"><i>Price : (per day)</i></span>
          <p style="padding-left:40px"><strong><font size="+5"><%= @morty.price%>$</strong></font></p>
        </font>
      </div>
      <div>
        <%= cl_image_tag @morty.photo.key, height: 325, width: 150%>
      </div>
    </div>
    <% if @reservation.user == current_user && (@reservation.favori.nil? || @reservation.favori == false) && @reservation.confirmation? %>
    <%= link_to reservation_path(@morty.reservations.last), method: :patch do %>
    <i class='far fa-heart'></i>
    <% end %>
    <% elsif  (@reservation.user == current_user && @reservation.favori == true)%>
    <i class="fas fa-heart"></i>
    <% end %>
  </div>


  <% if @reservation.pending? && @morty.user == current_user %>
  <div class="d-flex justify-content-center">
    <%= link_to "Validate", morty_path(@morty), class:"validation-button", method: :patch  %>
    <%= link_to "Reject", reservation_path(@reservation), class:"rejection-button", method: :delete  %>
  </div>
<% elsif @reservation.pending?%>
    <p class="status-text"> Your booking is pending confirmation</p>
<% elsif @reservation.confirmation?%>
  <p class="status-text"><%= @morty.name %> is already Booked</p>
<% elsif @morty.user == current_user  %>
  <p class="status-text">You are the owner of this Morty</p>
<% else %>
  <div class="w-50 text-center m-auto">
    <%= simple_form_for [@morty, @reservation] do |f| %>
      <%= f.button :submit, "Book this Morty !", class: "btn btn-black"%>
    <% end %>
  </div>
  <% end %>
    <div class="row card-large bg-light shadow p-5 margin-top-80px mb-5 bg-white d-flex justify-content-center text-center">
        <div class="header-shadow">Reviews</div>
        <div class="col-sm-offset-2 col-sm-8 d-flex justify-content-between my-3">
          <% if @morty.reviews.empty? %>
            <p style="padding-left: 150px">Be the first to let a review</p>
          <% else %>
             <ul class="list-group">
                <% @morty.reviews.each do |review| %>
              <li>
                <div class="review-content my-2">
                  <span class="badge badge-primary badge-pill">
                    <% counter = 0 %>
                    <% 5.times do %>
                      <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                      <% counter += 1 %>
                    <% end %>
                  </span>
                  <%= review.description %> - written by  <i> <%= review.user.first_name%> <%= review.user.last_name%>  </i>
                </div>
              </li>
                <% end %>
             </ul>
          <% end %>
        </div>
    </div>
    <div class="d-flex justify-content-center">
      <% if @reservation.present? && @reservation.user == current_user && @reservation.confirmation? %>
        <% if @morty.reviews.present?%>
          <% review_current_user = @morty.reviews.find do |review| review.user == current_user %>
          <% end %>
          <div >
            <% if review_current_user.nil? %>
              <%= link_to "Add a Review", new_morty_review_path(@morty), class: "btn btn-black"  %>
              <% end %>
        <% else %>
         <%= link_to "Add a Review", new_morty_review_path(@morty), class: "btn btn-black"  %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/my/morties/index.html.erb
<div class="container">
  <div class="last-morties">
    <h1 class="list-header">Hello <%= current_user.first_name %> <%= current_user.last_name %> </h1>
    <div class="home-headers">
      <% if @morties.empty?%>
        <h2>Mmmm... You haven't added a morty yet... <%= link_to new_morty_path(@morty), class: "home-btn-alternative" do %>What are you waiting for ?<% end %></h2>
        <br>
        <img class="img" src="https://media.giphy.com/media/3o85xE7pIsVXSKnIQg/giphy.gif">
      <% else %>
        <h2>My Morty's :</h2>
      <% end %>
      
    </div>
    <div class="cards-all">
    <% @morties.each do |morty| %>
        <% last_reservation = morty.reservations.last %>
        <% morty_display_image_condition = last_reservation.present? && last_reservation.confirmation? %>
        <%= render 'shared/cards-small', morty: morty, morty_display_image_condition: morty_display_image_condition %>
    <% end %>
    </div>
    
    <% if !current_user.reservations.empty? %>
      <h1 class="list-header">Your reservations</h1>
      <div class="home-headers">
        <div class="cards-all">
          <% current_user.confirmations.each do |confirmation| %>
           <% last_reservation = confirmation.morty.reservations.last %>
           <% morty_display_image_condition = last_reservation.present? && last_reservation.confirmation? %>
           <%= render 'shared/cards-small', morty: confirmation.morty, morty_display_image_condition: morty_display_image_condition %>
          <% end %>
        </div>
      </div>
    <% end %>
    
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="banner">
    <h1 class="banner-title">Rent a Morty <img src="https://media0.giphy.com/media/2cehgMhmxSp0LFKAws/source.gif" alt=""></h1>
      <%= simple_form_for :request, url: morties_path, method: :get  do |f| %>
        <div id="search">
          <div class="row justify-content-center align-items-center">
            <div class="col-12 d-flex justify-content-center">
              <div class="row w-50">
                <div class="col-9 px-2 my-auto">
                  <%= f.input :name, placeholder: "Type this little brat's name", label: false %>
                </div>
                <div class="col-3 d-flex px-0">
                  <%= f.button :submit, "Find your new Morty", class: "home-btn" %>
                </div>
              </div>
            </div>
          </div>
          <br>
          <div class="row justify-content-center align-items-center">
            <div class="col-3">
              <%= f.input :price, placeholder: "How much for him, you cheapfuck", collection: Morty::PRICE %>
            </div>
            <div class="col-3">
              <%= f.input :state, collection: Morty::STATE %>
            </div>
            <div class="col-3">
              <%= f.input :rarity, collection: Morty::RARITY %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="home-headers">
        <h2> Lazy and hungover ? <a href="#last-morties" class="home-btn-alternative " ><i class="fas fa-caret-down"></i> Scroll and find what we have ! <i class="fas fa-caret-down"></i></a></h2>
        <br>
        <h2> Need money after a crazy night on Pluton ? <%= link_to new_morty_path(@morty), class: "home-btn-alternative" do %><i class="fas fa-dollar-sign"></i> Share your Morty ! <i class="fas fa-dollar-sign"></i><% end %></h2>
      </div>
    <img src="https://static.wikia.nocookie.net/rickandmorty/images/4/41/Pickle_rick_transparent_edgetrimmed.png" alt="Rick and Morty" class="img-background" id="pickle-rick">
    <script>
    //sets a random absolute position to a html element; receives the html element
    function moveElmRand(elm){
    elm.style.position ='absolute';
    elm.style.top = Math.floor(Math.random()*90+5)+'%';
    elm.style.left = Math.floor(Math.random()*90+5)+'%';
    }

    //get the #btn_test
    var btn_test = document.querySelector('#pickle-rick');

    //register to call moveElmRand() on mouseenter event to #btn_test
    btn_test.addEventListener('mouseenter', function(e){ moveElmRand(e.target);});

    //register click to #btn_test
    btn_test.addEventListener('click', function(e){ alert('PICKLE RICK DICKHEAD !!!');});
    </script>
  </div>
  <div class="last-morties" id="last-morties">
    <h2 class="list-header"> Check our latest Morties : </h2>
      <div class="cards-all">
        <% @morties.last(6).each do |morty| %>
          <% last_reservation = morty.reservations.last %>
          <% morty_display_image_condition = last_reservation.present? && last_reservation.confirmation? %>
          <%= render 'shared/cards-small', morty: morty, morty_display_image_condition: morty_display_image_condition %>
        <% end %>
      </div>
  </div>
</div>

app/views/reservations/show.html.erb
<h1 class="h1-res">Your reservation is pending</h1>

<div class="card-container-res">
  <div class="card-res">
    <div class="front">
      <h1 class="title-res">
        Wubba Lubba Dub Dub!

      </h1>
      <img class="image-res" src="http://pre14.deviantart.net/0aef/th/pre/f/2014/015/2/f/look_at_that_thing_morty____rick_and_morty_by_kory226-d72a6ub.png" alt="" />
    </div>
    <div class="back">
      <h3 class="synopsis">First timer?</h3>
      <p class="p-res">The actual Rick owner will reach to you soon.</p>
        <%= link_to "Back to Morty", morty_path(@reservation.morty), class: "btn btn-flat" %>
    </div>
  </div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="card-large row morty-description bg-light shadow p-3 mb-5 bg-white justify-content-center mt-5">
    <h1 class="header-shadow">Add my Morty</h1>
    <div class="col-sm-offset-2 col-sm-8 my-2">
      <h3 class="py-2">Leave a review to <%= @morty.name %></h3>
      <%= simple_form_for [@morty, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :description %>
        <div class="text-center">
          <%= f.submit class: "btn btn-flat"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_cards-small.html.erb
<div>
  <%= link_to morty_path(morty) do %>
    <div class="card card-small">
      <%= image_tag "booked.png", alt: "booked", id: "booked-img-small" if morty_display_image_condition %>
      <%= cl_image_tag morty.photo.key %>
      <div class="card-body text-center">
        <h5 class="card-title header-shadow-small"><%= morty.name %> </h5>
        <p>State: <%= morty.state %></p>
        <p>Rarity: <%= morty.rarity %></p>
        <h6>Price: <%= morty.price %> $</h6>
      </div>
    </div>
  <% end %>
  <% if morty.reservations.last.present? && morty.reservations.last.pending? && current_page?(my_morties_path) %>
    <div class="btn-validate-reject">
      <%= link_to "Validate", morty_path(morty), class:"validation-button", method: :patch  %>
      <%= link_to "Reject", reservation_path(morty.reservations.last), class:"rejection-button", method: :delete  %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer>
    <p>App made with ❤️ by Antoine, Marco, Bryan & Maxime | Le Wagon #526</p>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="navbar-text">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "LogoRM.png" %>
    <% end %>

  <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <p class="nav-link"> Welcome <%= current_user.first_name %> ! You dickhead 🖕
          <% current_user.morties.find do |morty| %> 
              <% if morty.reservations.last.present? && morty.reservations.last.pending? %>
                <%= link_to "🚨 You have a new reservation ! 🚨", my_morties_path, class: "notification" %> 
              <% end %>
          <% end %> 
            </p>
        </li>
        <li class="nav-item dropdown">
          <%= avatar_navbar(current_user)%>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Morties", my_morties_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>